=== MMetze/DMHelper/DMHelper/src/resources/equipment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="magicitems"/>
                <xs:element name="armor">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element ref="heavyarmor"/>
                            <xs:element ref="lightarmor"/>
                            <xs:element ref="mediumarmor"/>
                            <xs:element ref="shield"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="weapons"/>
                <xs:element ref="animals"/>
                <xs:element ref="tacks"/>
                <xs:element ref="vehicles"/>
                <xs:element ref="tradegoods"/>
                <xs:element ref="lifestyleexpenses"/>
                <xs:element ref="food"/>
                <xs:element ref="service"/>
                <xs:element ref="tools"/>
                <xs:element ref="adventuringgear"/>
                <xs:element ref="containers"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="magicitems">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="magicitem"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="magicitem">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="subcategory"/>
            </xs:sequence>
            <xs:attribute name="attunement"/>
            <xs:attribute name="category" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="subcategory">
        <xs:complexType>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability"/>
            <xs:attribute name="category"/><!-- never used -->
            <xs:attribute name="attunement"/><!-- never used -->
        </xs:complexType>
    </xs:element>
    <xs:element name="weapons">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="simplemeleeweapons"/>
                <xs:element ref="simplerangedweapons"/>
                <xs:element ref="martialmeleeweapons"/>
                <xs:element ref="martialrangedweapons"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="simplemeleeweapons">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="weapon"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="simplerangedweapons">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="weapon"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="martialmeleeweapons">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="weapon"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="martialrangedweapons">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="weapon"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="animals">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="animal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="animal">
        <xs:complexType>
            <xs:attribute name="capacity" use="required"/>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" use="required"/>
            <xs:attribute name="speed" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="tacks">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="tack"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tack">
        <xs:complexType>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" use="required"/>
            <xs:attribute name="weight" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="vehicles">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="vehicle"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="vehicle">
        <xs:complexType>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" use="required"/>
            <xs:attribute name="speed" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="tradegoods">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="tradegood"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tradegood">
        <xs:complexType>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="lifestyleexpenses">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="lifestyle"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="lifestyle">
        <xs:complexType>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
            <xs:attribute name="probability" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="food">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="fooditem"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="fooditem">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="foodsubitem"/>
            </xs:sequence>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="foodsubitem">
        <xs:complexType>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="service">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="serviceitem"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="serviceitem">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="servicesubitem"/>
            </xs:sequence>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="servicesubitem">
        <xs:complexType>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="tools">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="tool"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tool">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="subtool"/>
            </xs:sequence>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability"/>
            <xs:attribute name="weight" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="subtool">
        <xs:complexType>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" use="required"/>
            <xs:attribute name="weight" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="adventuringgear">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="gear"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="gear">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="subgear"/>
            </xs:sequence>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability"/>
            <xs:attribute name="weight" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="subgear">
        <xs:complexType>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" use="required"/>
            <xs:attribute name="weight" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="containers">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element maxOccurs="unbounded" ref="container"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="container">
        <xs:complexType>
            <xs:attribute name="capacity" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="heavyarmor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="armor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="ac"/>
                        <xs:attribute name="cost"/>
                        <xs:attribute name="probability"/>
                        <xs:attribute name="stealth" type="xs:NMTOKEN"/>
                        <xs:attribute name="strength"/>
                        <xs:attribute name="type"/>
                        <xs:attribute name="weight"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="lightarmor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="armor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="ac"/>
                        <xs:attribute name="cost"/>
                        <xs:attribute name="probability"/>
                        <xs:attribute name="stealth" type="xs:NMTOKEN"/>
                        <xs:attribute name="strength"/>
                        <xs:attribute name="type"/>
                        <xs:attribute name="weight"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="mediumarmor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="armor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="ac"/>
                        <xs:attribute name="cost"/>
                        <xs:attribute name="probability"/>
                        <xs:attribute name="stealth" type="xs:NMTOKEN"/>
                        <xs:attribute name="strength"/>
                        <xs:attribute name="type"/>
                        <xs:attribute name="weight"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="shield">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="armor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="ac"/>
                        <xs:attribute name="cost"/>
                        <xs:attribute name="probability"/>
                        <xs:attribute name="stealth" type="xs:NMTOKEN"/>
                        <xs:attribute name="strength"/>
                        <xs:attribute name="type"/>
                        <xs:attribute name="weight"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="weapon">
        <xs:complexType>
            <xs:attribute name="cost" use="required"/>
            <xs:attribute name="damage" use="required"/>
            <xs:attribute name="name" use="required"/>
            <xs:attribute name="probability" use="required" type="xs:NCName"/>
            <xs:attribute name="properties" use="required"/>
            <xs:attribute name="weight" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MMetze/DMHelper/DMHelper/src/resources/equipment.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="equipment.xsd">
    <magicitems>
        <magicitem name="Adamantine Armor" category="Armor (medium or heavy, but not hide)" probability="uncommon" attunement=""/>
        <magicitem name="Ammunition, +1" category="Weapon (any ammunition)" probability="uncommon" attunement=""/>
        <magicitem name="Ammunition, +2" category="Weapon (any ammunition)" probability="rare" attunement=""/>
        <magicitem name="Ammunition, +3" category="Weapon (any ammunition)" probability="very rare" attunement=""/>
        <magicitem name="Amulet of Health" category="Wondrous item" probability="rare" attunement="y"/>
        <magicitem name="Amulet of the Planes" category="Wondrous item" probability="very rare" attunement="y"/>
        <magicitem name="Animated Shield" category="Armor (shield)" probability="very rare" attunement="y"/>
        <magicitem name="Apparatus of the Crab" category="Wondrous item" probability="legendary" attunement=""/>
        <magicitem name="Armor, +1" category="Armor (light, medium, or heavy)" probability="rare" attunement=""/>
        <magicitem name="Armor, +2" category="Armor (light, medium, or heavy)" probability="very rare" attunement=""/>
        <magicitem name="Armor, +3" category="Armor (light, medium, or heavy)" probability="legendary" attunement=""/>
        <magicitem name="Armor of Invulnerability" category="Armor (plate)" probability="legendary" attunement="y"/>
        <magicitem name="Armor of Resistance" category="Armor (light, medium, or heavy)" probability="rare" attunement="y">
            <subcategory name="Acid" category="" probability="" attunement=""/>
            <subcategory name="Cold" category="" probability="" attunement=""/>
            <subcategory name="Fire" category="" probability="" attunement=""/>
            <subcategory name="Force" category="" probability="" attunement=""/>
            <subcategory name="Lightning" category="" probability="" attunement=""/>
            <subcategory name="Necrotic" category="" probability="" attunement=""/>
            <subcategory name="Poison" category="" probability="" attunement=""/>
            <subcategory name="Psychic" category="" probability="" attunement=""/>
            <subcategory name="Radiant" category="" probability="" attunement=""/>
            <subcategory name="Thunder" category="" probability="" attunement=""/>
        </magicitem>
        <magicitem name="Armor of Vulnerability" category="Armor (plate)" probability="rare" attunement="y"/>
        <magicitem name="Arrow-Catching Shield" category="Armor (shield)" probability="rare" attunement="y"/>
        <magicitem name="Arrow of Slaying" category="Weapon (arrow)" probability="very rare" attunement=""/>
        <magicitem name="Bag of Beans" category="Wondrous item" probability="rare" attunement=""/>
        <magicitem name="Bag of Devouring" category="Wondrous item" probability="very rare" attunement=""/>
        <magicitem name="Bag of Holding" category="Wondrous item" probability="uncommon" attunement=""/>
        <magicitem name="Bag of Tricks" category="Wondrous item" probability="uncommon" attunement="">
            <subcategory name="Gray Bag of Tricks" category="" probability="" attunement=""/>
            <subcategory name="Rust Bag of Tricks" category="" probability="" attunement=""/>
            <subcategory name="Tan Bag of Tricks" category="" probability="" attunement=""/>
        </magicitem>
        <magicitem name="Bead of Force" category="Wondrous item" probability="rare" attunement=""/>
        <magicitem name="Belt of Dwarvenkind" category="Wondrous item" probability="rare" attunement="y"/>
        <magicitem name="Belt of Giant Strength" category="Wondrous item" probability="" attunement="y">
            <subcategory name="Hill giant" category="" probability="rare" attunement=""/>
            <subcategory name="Stone giant" category="" probability="very rare" attunement=""/>
            <subcategory name="Frost giant" category="" probability="very rare" attunement=""/>
            <subcategory name="Fire giant" category="" probability="very rare" attunement=""/>
            <subcategory name="Cloud giant" category="" probability="legendary" attunement=""/>
            <subcategory name="Storm giant" category="" probability="legendary" attunement=""/>
        </magicitem>
        <magicitem name="Berserker Axe" category="Weapon (any axe)" probability="rare" attunement="y"/>
        <magicitem name="Boots of Elvenkind" category="Wondrous item" probability="uncommon" attunement=""/>
        <magicitem name="Boots of Levitation" category="Wondrous item" probability="rare" attunement="y"/>
        <magicitem name="Boots of Speed" category="Wondrous item" probability="rare" attunement="y"/>
        <magicitem name="Boots of Striding and Springing" category="Wondrous item" probability="uncommon" attunement="y"/>
        <magicitem name="Boots of the Winterlands" category="Wondrous item" probability="uncommon" attunement="y"/>
        <magicitem name="Bowl of Commanding Water Elementals" category="Wondrous item" probability="rare" attunement=""/>
        <magicitem name="Bracers of Archery" category="Wondrous item" probability="uncommon" attunement="y"/>
        <magicitem name="Bracers of Defense" category="Wondrous item" probability="rare" attunement="y"/>
        <magicitem name="Brazier of Commanding Fire Elementals" category="Wondrous item" probability="rare" attunement=""/>
        <magicitem name="Brooch of Shielding" category="Wondrous item" probability="uncommon" attunement="y"/>
        <magicitem name="Broom of Flying" category="Wondrous item" probability="uncommon" attunement=""/>
        <magicitem name="Candle of Invocation" category="Wondrous item" probability="very rare" attunement="y">
            <subcategory name="Chaotic evil" category="" probability="" attunement=""/>
            <subcategory name="Chaotic neutral" category="" probability="" attunement=""/>
            <subcategory name="Chaotic good" category="" probability="" attunement=""/>
            <subcategory name="Neutral evil" category="" probability="" attunement=""/>
            <subcategory name="Neutral" category="" probability="" attunement=""/>
            <subcategory name="Neutral good" category="" probability="" attunement=""/>
            <subcategory name="Lawful evil" category="" probability="" attunement=""/>
            <subcategory name="Lawful neutral" category="" probability="" attunement=""/>
            <subcategory name="Lawful good" category="" probability="" attunement=""/>
        </magicitem>
        <magicitem name="Cape of the Mountebank" category="Wondrous item" probability="rare" attunement=""/>
        <magicitem name="Carpet of Flying" category="Wondrous item" probability="very rare" attunement="">
            <subcategory name="3ft. x 5 ft." category="" probability="" attunement=""/>
            <subcategory name="4ft. x 6ft." category="" probability="" attunement=""/>
            <subcategory name="5ft. x 7 ft." category="" probability="" attunement=""/>
            <subcategory name="6ft. x 9 ft." category="" probability="" attunement=""/>
        </magicitem>
        <magicitem name="Censer of Controlling Air Elementals" category="Wondrous item" probability="rare" attunement=""/>
        <magicitem name="Censer of Controlling Earth Elementals" category="Wondrous item" probability="rare" attunement=""/>
        <magicitem name="Censer of Controlling Fire Elementals" category="Wondrous item" probability="rare" attunement=""/>
        <magicitem name="Censer of Controlling Water Elementals" category="Wondrous item" probability="rare" attunement=""/>
        <magicitem name="Chime of Opening" category="Wondrous item" probability="rare" attunement=""/>
        <magicitem name="Circlet of Blasting" category="Wondrous item" probability="uncommon" attunement=""/>
        <magicitem name="Cloak of Arachnida" category="Wondrous item" probability="very rare" attunement="y"/>
        <magicitem name="Cloak of Displacement" category="Wondrous item" probability="rare" attunement="y"/>
        <magicitem name="Cloak of Elvenkind" category="Wondrous item" probability="uncommon" attunement="y"/>
        <magicitem name="Cloak of Protection" category="Wondrous item" probability="uncommon" attunement="y"/>
        <magicitem name="Cloak of the Bat" category="Wondrous item" probability="rare" attunement="y"/>
        <magicitem name="Cloak of the Manta Ray" category="Wondrous item" probability="uncommon" attunement=""/>
        <magicitem name="Crystal Ball" category="Wondrous item" probability="very rare" attunement="y"/>
        <magicitem name="Crystal Ball of Mind Reading" category="Wondrous item" probability="legendary" attunement="y"/>
        <magicitem name="Crystal Ball of Telepathy" category="Wondrous item" probability="legendary" attunement="y"/>
        <magicitem name="Crystal Ball of True Seeing" category="Wondrous item" probability="legendary" attunement="y"/>
        <magicitem name="Cube of Force" category="Wondrous item" probability="rare" attunement="y"/>
        <magicitem name="Cubic Gate" category="Wondrous item" probability="legendary" attunement=""/>
        <magicitem name="Dagger of Venom" category="Weapon (dagger)" probability="rare" attunement=""/>
        <magicitem name="Dancing Sword" category="Weapon (any sword)" probability="very rare" attunement="y"/>
        <magicitem name="Decanter of Endless Water" category="Wondrous item" probability="uncommon" attunement=""/>
        <magicitem name="Deck of Illusions" category="Wondrous item" probability="uncommon" attunement=""/>
        <magicitem name="Deck of many things" category="Wondrous item" probability="legendary" attunement=""/>
        <magicitem name="Defender" category="Weapon (any sword)" probability="legendary" attunement="y"/>
