=== MMetze/DMHelper/DMHelper/src/resources/tables/table.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="dmhelperlist">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="entry"/>
            </xs:sequence>
            <xs:attribute name="name" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="entry">
        <xs:complexType mixed="true">
            <xs:attribute name="subtable" use="optional"/>
            <xs:attribute name="weight" use="optional" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MMetze/DMHelper/DMHelper/src/resources/tables/Indefinite Madness.xml
<?xml version="1.0" encoding="UTF-8"?>
<dmhelperlist name="Indefinite Madness" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="table.xsd">
    <entry weight="15">"Being drunk keeps me sane."</entry>
    <entry weight="10">"I keep whatever I find."</entry>
    <entry weight="5">"I try to become more like someone else I know-adopting his or her style of dress, mannerisms, and name."</entry>
    <entry weight="5">"I must bend the truth, exaggerate, or outright lie to be interesting to other people."</entry>
    <entry weight="10">"Achieving my goal is the only thing of interest to me, and I'll ignore everything else to pursue it."</entry>
    <entry weight="5">"I find it hard to care about anything that goes on around me."</entry>
    <entry weight="5">"I don't like the way people judge me all the time."</entry>
    <entry weight="15">"I am the smartest, wisest, strongest, fastest, and most beautiful person I know."</entry>
    <entry weight="10">"I am convinced that powerful enemies are hunting me, and their agents are everywhere I go. I am sure they're watching me all the time."</entry>
    <entry weight="5">"There's only one person I can trust. And only I can see this special friend."</entry>
    <entry weight="10">"I can't take anything seriously. The more serious the situation, the funnier I find it."</entry>
    <entry weight="5">"I've discovered that I really like killing people."</entry>
</dmhelperlist>
